// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPzvhX9YCqXPHXmd3jHK597Ggwkls6wU',
    appId: '1:170517542981:web:15a26562b5a89fc9db4b2c',
    messagingSenderId: '170517542981',
    projectId: 'fireauth-d75fe',
    authDomain: 'fireauth-d75fe.firebaseapp.com',
    storageBucket: 'fireauth-d75fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcpoANh20wYUj0NnBvSyfFkGHlK0yGbaM',
    appId: '1:170517542981:android:3d925c0c1a2d1c71db4b2c',
    messagingSenderId: '170517542981',
    projectId: 'fireauth-d75fe',
    storageBucket: 'fireauth-d75fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnsTcEqCSLbNOEb31gEkQ-dx3lK2V_K0',
    appId: '1:170517542981:ios:8da41618018c7bdadb4b2c',
    messagingSenderId: '170517542981',
    projectId: 'fireauth-d75fe',
    storageBucket: 'fireauth-d75fe.appspot.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnsTcEqCSLbNOEb31gEkQ-dx3lK2V_K0',
    appId: '1:170517542981:ios:0f4934bc3cebcac1db4b2c',
    messagingSenderId: '170517542981',
    projectId: 'fireauth-d75fe',
    storageBucket: 'fireauth-d75fe.appspot.com',
    iosBundleId: 'com.example.fireauth.RunnerTests',
  );
}
